---
title: "DHGLMs"
author: "Tali Caspi"
date: "2025-03-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggpubr);library(lme4);library(arm);library(MuMIn);library(tidyverse)
library(broom);library(coda);library(grid);
library(gridExtra);library(brms); library(broom.mixed); library(merTools);
library(tidybayes);library(parallel); library(bayesplot); library(DHARMa.helpers); library(DHARMa); library(bayestestR); library(plotrix)

# Make custom theme
theme_custom <- function() {
  theme_classic()+
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(size = 12, face = "bold"),
        plot.background = element_rect(fill = "white", color = NA),
        plot.title = element_text(size = 7),
        strip.background = element_blank(),
        axis.text.y = element_text(size=5),
        axis.text.x = element_text(size=10),
        axis.title.y = element_text(size=12),
        axis.title.x = element_text(size=12))}

select <- dplyr::select
```

# Prepare data

```{r}
# Load data frame
data <- read.csv("Cleaned_Data/cleaned_whiskerdata.csv")

# Create df for models
dhglm_df <- data %>% 
  dplyr::select(SampleID, seg_num, C_raw, N_raw, individual, whisker, count, urban, sex) %>% 
  filter(count >=3) # remove whiskers with less than three segments

nrow(dhglm_df) # 14167 whisker segments

# Investigate data distribution
ggdensity(scale(dhglm_df$C_raw)) # left skew
ggdensity(scale(dhglm_df$N_raw)) # right skew

ggqqplot(scale(dhglm_df$C_raw))
ggqqplot(scale(dhglm_df$N_raw))

# Sample counts
dhglm_df_counts <- dhglm_df %>% distinct(individual, urban)
table(dhglm_df_counts$urban) # 8 Marin coyotes and 96 SF coyotes
```

Data are skewed - apply skew normal distribution.

```{r}
my.cores <- detectCores()

# Construct models
dhglm_N <- bf(scale(N_raw) ~ urban + sex + (1|a|whisker),
               sigma ~ urban + sex + (1|a|whisker))

dhglm_N_skew <- brm(dhglm_N,
              data   = dhglm_df, 
              family = skew_normal(),
              warmup = 1000,iter = 5000, thin=2,
              chains = 4,
              seed = 12345,
              cores  = my.cores,
              control = list(adapt_delta = 0.95))

dhglm_C <- bf(scale(C_raw) ~ urban + sex + (1|a|whisker),
               sigma ~ urban + sex + (1|a|whisker))

dhglm_C_skew <- brm(dhglm_C,
              data   = dhglm_df, 
              family = skew_normal(),
              warmup = 1000,iter = 5000, thin=2,
              chains = 4,
              seed = 12345,
              cores  = my.cores,
              control = list(adapt_delta = 0.95))

# Set prior for bivariate model
priors <- c(
  # Priors for fixed effects
  set_prior("normal(0, 4)", class = "b"),                       
  set_prior("student_t(3, -0.1, 2.5)", class = "Intercept", resp = "scaleNraw"),
  set_prior("student_t(3, 0, 2.5)", class = "Intercept", resp = "scaleCraw"), 
  
  # Priors for random effects
  set_prior("student_t(3, 0, 2.5)", class = "sd", group = "whisker", resp = "scaleNraw"),
  set_prior("student_t(3, 0, 2.5)", class = "sd", group = "whisker", resp = "scaleCraw"),
  
  # Priors for residual standard deviation
  set_prior("student_t(3, 0, 2.5)", class = "sigma", resp = "scaleNraw"),
  set_prior("student_t(3, 0, 2.5)", class = "sigma", resp = "scaleCraw"),
  
  # Prior for correlations
  set_prior("lkj(2)", class = "cor")
)

bivariate_model <- brm(dhglm_N + dhglm_C + set_rescor(FALSE),
                 data = dhglm_df,
                  family = skew_normal(),
                    #prior=priors,
                    warmup = 1000, iter = 5000, thin=2,
                    chains = 4,
                    seed = 12345,
                    cores  = my.cores,
                    control = list(adapt_delta = 0.95))
# Save models
# saveRDS(dhglm_N_skew, "Model_Output/dhglm_N_skew.rds")
# saveRDS(dhglm_C_skew, "Model_Output/dhglm_C_skew.rds")
# saveRDS(bivariate_model, "Model_Output/bivariate_model.rds")

# Load models
dhglm_N_skew <- readRDS("Model_Output/dhglm_N_skew.rds")
dhglm_C_skew <- readRDS("Model_Output/dhglm_C_skew.rds")
bivariate_model <- readRDS("Model_Output/bivariate_model.rds")
```

# Assess model fit and covariate effects

```{R}
# Check model fit
pp_check(dhglm_N_skew, ndraws=100)
dh_check_brms(dhglm_N_skew)

pp_check(dhglm_C_skew, ndraws=100)
dh_check_brms(dhglm_C_skew)

pp_check(bivariate_model, resp="scaleCraw", ndraws=100)
pp_check(bivariate_model, resp="scaleNraw", ndraws=100)
dh_check_brms(bivariate_model, resp="scaleNraw")
dh_check_brms(bivariate_model, resp="scaleCraw")

# Conditional effects
conditional_effects(dhglm_C_skew) # urban sig; sex not
conditional_effects(dhglm_N_skew) # urban sig; sex not
conditional_effects(bivariate_model)

# R2
performance::r2_bayes(dhglm_N_skew)
performance::r2_bayes(dhglm_C_skew)
performance::r2_bayes(bivariate_model)

# ICC
ICC(data=dhglm_df, outcome="N_raw", group="whisker")
ICC(data=dhglm_df, outcome="C_raw", group="whisker")
```

# Extract model results

```{r}
colnames(posterior_samples(dhglm_N_skew))[1:8]

# Extract model results
models_dhglm <- list(
  dhglm_N_skew = dhglm_N_skew,
  dhglm_C_skew = dhglm_C_skew)

# Function to summarize posterior estimates and calculate 95% HPD using coda's HPDinterval
summarize_posteriors_dhglm <- function(model, model_name) {
  posterior_estimates <- posterior_samples(model)[1:8]  # Use as_draws for extraction
  
  do.call(rbind, lapply(names(posterior_estimates), function(param) {
    values <- posterior_estimates[[param]]
    
    # Convert the values to an MCMC object
    mcmc_values <- as.mcmc(values)
    
    # Calculate the 95% HPD interval using coda::HPDinterval
    hpd_vals <- HPDinterval(mcmc_values, prob = 0.95)
    
    # Create a data frame for the results
    data.frame(
      Model = model_name,
      Effect = param,
      Estimate = round(mean(values, na.rm = TRUE), 4),
      lower = round(hpd_vals[1], 4),
      upper = round(hpd_vals[2], 4)
    )
  }))
}

# Loop through all models and combine results
dhglm_results <- do.call(rbind, lapply(names(models_dhglm), function(model_name) {
  summarize_posteriors_dhglm(models_dhglm[[model_name]], model_name)
}))

custom_order <- c("b_Intercept", "b_urbanurban", "b_sexmale", "sd_whisker__Intercept", "b_sigma_Intercept", "b_sigma_urbanurban", "b_sigma_sexmale", "sd_whisker__sigma_Intercept")

dhglm_results <- dhglm_results %>% 
  mutate(Effect = factor(Effect, levels = custom_order)) %>%
  arrange(Effect) %>% 
  group_by(Effect) %>%
  mutate(Result = paste(Estimate, " (", lower, ", ", upper, ")", sep = "")) %>%
  select(-c(Estimate, lower, upper)) %>% 
  pivot_wider(
    names_from = Model,
    values_from = Result
  ) 

dhglm_results
```


# Repeatability

```{r}
# Extract site-specific individuals
urban_ids <- dhglm_df %>% filter(urban == "urban") %>% pull(whisker) %>% unique()
nonurban_ids <- dhglm_df %>% filter(urban == "nonurban") %>% pull(whisker) %>% unique()

# Variance Components
posterior_samples_N <- posterior_samples(dhglm_N_skew)
posterior_samples_C <- posterior_samples(dhglm_C_skew)

# Extract random effects for each site
urban_effects_N <- posterior_samples_N %>%
  dplyr::select(matches(paste0("r_whisker\\[(", paste(urban_ids, collapse = "|"), "),Intercept\\]")))

nonurban_effects_N <- posterior_samples_N %>%
  dplyr::select(matches(paste0("r_whisker\\[(", paste(nonurban_ids, collapse = "|"), "),Intercept\\]")))

urban_effects_C <- posterior_samples_C %>%
  dplyr::select(matches(paste0("r_whisker\\[(", paste(urban_ids, collapse = "|"), "),Intercept\\]")))

nonurban_effects_C <- posterior_samples_C %>%
  dplyr::select(matches(paste0("r_whisker\\[(", paste(nonurban_ids, collapse = "|"), "),Intercept\\]")))

# Calculate whisker variances
var_whisker_urban_N <- apply(urban_effects_N, 1, var)
var_whisker_nonurban_N <- apply(nonurban_effects_N, 1, var)
var_whisker_urban_C <- apply(urban_effects_C, 1, var)
var_whisker_nonurban_C <- apply(nonurban_effects_C, 1, var)

# Calculate residual variances
var_residual_urban_N <- (exp(posterior_samples_N$`b_sigma_Intercept` +
                           posterior_samples_N$`b_sigma_urbanurban`))^2
var_residual_nonurban_N <- (exp(posterior_samples_N$`b_sigma_Intercept`))^2
var_residual_urban_C <- (exp(posterior_samples_C$`b_sigma_Intercept` +
                           posterior_samples_C$`b_sigma_urbanurban`))^2
var_residual_nonurban_C <- (exp(posterior_samples_C$`b_sigma_Intercept`))^2

# Calculate repeatability for each group
rpt_urban_N <- var_whisker_urban_N / (var_whisker_urban_N + var_residual_urban_N)
rpt_nonurban_N <- var_whisker_nonurban_N / (var_whisker_nonurban_N + var_residual_nonurban_N)
rpt_urban_C <- var_whisker_urban_C / (var_whisker_urban_C + var_residual_urban_C)
rpt_nonurban_C <- var_whisker_nonurban_C / (var_whisker_nonurban_C + var_residual_nonurban_C)

mean(rpt_urban_N);bci(rpt_urban_N) # urban N
mean(rpt_nonurban_N);bci(rpt_nonurban_N) # nonurban N
mean(rpt_urban_C);bci(rpt_urban_C) # urban C
mean(rpt_nonurban_C);bci(rpt_nonurban_C) # nonurban C
```

# Plot

## Carbon

```{r}
s.C_raw <- scale(dhglm_df$C_raw)

colnames(posterior_samples(dhglm_C_skew))

# Mean Carbon
posterior_type_C <- posterior_samples(dhglm_C_skew)[,11:114] %>%
  gather(whisker, value, 
         "r_whisker[S19-8741,Intercept]" : "r_whisker[S24-1425,Intercept]")%>%
  separate(whisker, 
           c(NA,NA,"whisker",NA), 
           sep = "([\\_\\[\\,])", fill = "right") %>%
  left_join(dplyr::select(dhglm_df[!duplicated(dhglm_df$whisker),],whisker, sex, urban, count))

# Add population intercept and coefficient for sex and urban to each value
posterior_type_C[posterior_type_C$sex == "female",]$value <- 
  posterior_type_C[posterior_type_C$sex == "female",]$value + fixef(dhglm_C_skew, pars = "Intercept")[1]

posterior_type_C[posterior_type_C$sex == "male",]$value <- 
  posterior_type_C[posterior_type_C$sex == "male",]$value + fixef(dhglm_C_skew, pars = "Intercept")[1] +  fixef(dhglm_C_skew, pars = "sexmale")[1] 

posterior_type_C[posterior_type_C$urban == "urban",]$value <- 
  posterior_type_C[posterior_type_C$urban == "urban",]$value + fixef(dhglm_C_skew, pars = "urbanurban")[1] 

# Calculate individual means and back-transform
posterior_type_C <- posterior_type_C %>%
    dplyr::group_by(whisker) %>%
    dplyr::mutate(value_tf= value * attr(s.C_raw, 'scaled:scale')+ 
                      attr(s.C_raw, 'scaled:center'),
                  hpd = list(HPDinterval(as.mcmc(value_tf), prob = 0.95)),
                  lower = hpd[[1]][1],
                  upper = hpd[[1]][2]) %>% 
    filter(value_tf >= lower & value_tf <= upper) %>% 
    dplyr::mutate(mean_C = mean(value_tf)) %>%
    dplyr::ungroup()

# Plot
fig.3a <- ggplot() +
  geom_errorbar(data = posterior_type_C[!duplicated(posterior_type_C$whisker),], 
                aes(y = mean_C, ymin = lower, ymax = upper, 
                    x= reorder(as.factor(whisker), mean_C), color=urban),
                width = 0, linewidth=0.5) +
  geom_point(data = posterior_type_C[!duplicated(posterior_type_C$whisker),],
             aes(y = mean_C,  x= reorder(as.factor(whisker), mean_C), shape = sex),
             size = 0.7, color = "black") +
  labs(x = "Individual", y = expression("Mean"~delta^{13}~C)) +
  scale_y_continuous(limits=c(-24.3,-15), breaks=seq(-24,-15,by=1)) +
  theme_custom() +
  scale_color_manual(values = c("urban" = "#c0362d", "nonurban" = "#284A45")) +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

fig.3a


# rIIV Carbon
posterior_var_C <- posterior_samples(dhglm_C_skew)[,115:218] %>%
  gather(whisker, value, 
         "r_whisker__sigma[S19-8741,Intercept]" : "r_whisker__sigma[S24-1425,Intercept]")%>%
  separate(whisker, c(NA,NA,NA,NA,"whisker",NA), 
           sep = "([\\__\\[\\,])", fill = "right") %>%
  left_join(dplyr::select(dhglm_df[!duplicated(dhglm_df$whisker),],whisker, sex, urban, count))

# Add population level mean residual variance and coefficients for sex and urban to each value
posterior_var_C[posterior_var_C$sex == "female",]$value <- 
  posterior_var_C[posterior_var_C$sex == "female",]$value + fixef(dhglm_C_skew, pars = "sigma_Intercept")[1]

posterior_var_C[posterior_var_C$sex == "male",]$value <- 
  posterior_var_C[posterior_var_C$sex == "male",]$value + fixef(dhglm_C_skew, pars = "sigma_Intercept")[1] +  fixef(dhglm_C_skew, pars = "sigma_sexmale")[1] 

posterior_var_C[posterior_var_C$urban == "urban",]$value <- 
  posterior_var_C[posterior_var_C$urban == "urban",]$value + fixef(dhglm_C_skew, pars = "sigma_urbanurban")[1] 

# exponentiate to get back to original scale, calculate mean values per individual, and back-transform
posterior_var_C <- posterior_var_C %>%
  dplyr::group_by(whisker) %>%
  dplyr::mutate(exp_value = exp(value),
                meanrIIV = mean(exp_value),
                rIIV_tf = exp_value * sd(dhglm_df$C_raw),
                mean_rIIV_tf = meanrIIV * sd(dhglm_df$C_raw),
                hpd = list(HPDinterval(as.mcmc(rIIV_tf), prob = 0.95)),
                lower = hpd[[1]][1],
                upper = hpd[[1]][2]) %>% 
  filter(rIIV_tf >= lower & rIIV_tf <= upper) %>% 
  dplyr::ungroup()

# plot
fig.3c <- ggplot() +
  geom_errorbar(data = posterior_var_C[!duplicated(posterior_var_C$whisker),], 
                aes(y = mean_rIIV_tf, ymin = lower, ymax = upper, 
                    x= reorder(as.factor(whisker), mean_rIIV_tf), color=urban),
                width = 0, linewidth=0.5) +
  geom_point(data = posterior_var_C[!duplicated(posterior_var_C$whisker),],
             aes(y = mean_rIIV_tf,  x= reorder(as.factor(whisker), mean_rIIV_tf), shape = sex),
             size = 0.7, color = "black") +
  labs(x = "Individual", y = expression("rIIV"~delta^{13}~C)) +
  scale_y_continuous(limits=c(0,3), breaks=c(0,1,2,3))+
  theme_custom() +
  scale_color_manual(values = c("urban" = "#c0362d", "nonurban" = "#284A45")) +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

fig.3c
```

## Nitrogen

```{r}
s.N_raw <- scale(dhglm_df$N_raw)

colnames(posterior_samples(dhglm_N_skew))

## Mean nitrogen
posterior_type_N <- posterior_samples(dhglm_N_skew)[,11:114] %>%
  gather(whisker, value, 
         "r_whisker[S19-8741,Intercept]" : "r_whisker[S24-1425,Intercept]")%>%
  separate(whisker, 
           c(NA,NA,"whisker",NA), 
           sep = "([\\_\\[\\,])", fill = "right") %>%
  left_join(dplyr::select(dhglm_df[!duplicated(dhglm_df$whisker),],whisker, sex, urban, count))

# Add population intercept and coefficient for sex and urban to each value
posterior_type_N[posterior_type_N$sex == "female",]$value <- 
  posterior_type_N[posterior_type_N$sex == "female",]$value + fixef(dhglm_N_skew, pars = "Intercept")[1]

posterior_type_N[posterior_type_N$sex == "male",]$value <- 
  posterior_type_N[posterior_type_N$sex == "male",]$value + fixef(dhglm_N_skew, pars = "Intercept")[1] +  fixef(dhglm_N_skew, pars = "sexmale")[1] 

posterior_type_N[posterior_type_N$urban == "urban",]$value <- 
  posterior_type_N[posterior_type_N$urban == "urban",]$value + fixef(dhglm_N_skew, pars = "urbanurban")[1] 

# Calculate individual means and back-transform
posterior_type_N <- posterior_type_N %>%
    dplyr::group_by(whisker) %>%
    dplyr::mutate(value_tf= value * attr(s.N_raw, 'scaled:scale')+ 
                      attr(s.N_raw, 'scaled:center'),
                  hpd = list(HPDinterval(as.mcmc(value_tf), prob = 0.95)),
                  lower = hpd[[1]][1],
                  upper = hpd[[1]][2]) %>% 
    filter(value_tf >= lower & value_tf <= upper) %>% 
    dplyr::mutate(mean_N = mean(value_tf)) %>%
    dplyr::ungroup()

# Plot
fig.3b <- ggplot() +
  geom_errorbar(data = posterior_type_N[!duplicated(posterior_type_N$whisker),], 
                aes(y = mean_N, ymin = lower, ymax = upper, 
                    x= reorder(as.factor(whisker), mean_N), color=urban),
                width = 0, linewidth=0.5) +
  geom_point(data = posterior_type_N[!duplicated(posterior_type_N$whisker),],
             aes(y = mean_N,  x= reorder(as.factor(whisker), mean_N), shape = sex),
             size = 0.7, color = "black") +
  labs(x = "Individual", y = expression("Mean"~delta^{15}~N)) +
  scale_y_continuous(limits=c(6,12.1), breaks=c(6,7,8,9,10,11,12)) +
  theme_custom() +
  scale_color_manual(values = c("urban" = "#c0362d", "nonurban" = "#284A45")) +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

fig.3b

# rIIV Nitrogen
posterior_var_N <- posterior_samples(dhglm_N_skew)[,115:218] %>%
  gather(whisker, value, 
         "r_whisker__sigma[S19-8741,Intercept]" : "r_whisker__sigma[S24-1425,Intercept]")%>%
  separate(whisker, c(NA,NA,NA,NA,"whisker",NA), 
           sep = "([\\__\\[\\,])", fill = "right") %>%
  left_join(dplyr::select(dhglm_df[!duplicated(dhglm_df$whisker),],whisker, sex, urban, count))

# Add population level mean residual variance and coefficients for sex and urban to each value
posterior_var_N[posterior_var_N$sex == "female",]$value <- 
  posterior_var_N[posterior_var_N$sex == "female",]$value + fixef(dhglm_N_skew, pars = "sigma_Intercept")[1]

posterior_var_N[posterior_var_N$sex == "male",]$value <- 
  posterior_var_N[posterior_var_N$sex == "male",]$value + fixef(dhglm_N_skew, pars = "sigma_Intercept")[1] +  fixef(dhglm_N_skew, pars = "sigma_sexmale")[1] 

posterior_var_N[posterior_var_N$urban == "urban",]$value <- 
  posterior_var_N[posterior_var_N$urban == "urban",]$value + fixef(dhglm_N_skew, pars = "sigma_urbanurban")[1] 


# exponentiate to get back to original scale, apply 95% HPD, calculate mean values per individual, and back-transform
posterior_var_N <- posterior_var_N %>%
  dplyr::group_by(whisker) %>%
  dplyr::mutate(exp_value = exp(value),
                meanrIIV = mean(exp_value),
                rIIV_tf = exp_value * sd(dhglm_df$N_raw),
                mean_rIIV_tf = meanrIIV * sd(dhglm_df$N_raw),
                hpd = list(HPDinterval(as.mcmc(rIIV_tf), prob = 0.95)),
                lower = hpd[[1]][1],
                upper = hpd[[1]][2]) %>% 
  filter(rIIV_tf >= lower & rIIV_tf <= upper) %>% 
  dplyr::ungroup()

# plot
fig.3d <- ggplot() +
  geom_errorbar(data = posterior_var_N[!duplicated(posterior_var_N$whisker),], 
                aes(y = mean_rIIV_tf, ymin = lower, ymax = upper, 
                    x= reorder(as.factor(whisker), mean_rIIV_tf), color=urban),
                width = 0, linewidth=0.5) +
  geom_point(data = posterior_var_N[!duplicated(posterior_var_N$whisker),],
             aes(y = mean_rIIV_tf,  x= reorder(as.factor(whisker), mean_rIIV_tf), shape = sex),
             size = 0.7, color = "black") +
  labs(x = "Individual", y = expression("rIIV"~delta^{15}~N)) +
  scale_y_continuous(limits=c(0,3), breaks=c(0,1,2,3))+
  theme_custom() +
  scale_color_manual(values = c("urban" = "#c0362d", "nonurban" = "#284A45")) +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

fig.3d
```

## Arrange plots

To complete figure 3, fig 3e and 3f must be generated in the SIBER.Rmd file.

```{r}
ggarrange(
  fig.3a, fig.3b, fig.3c, fig.3d, fig.3e, fig.3f,
  ncol = 2, nrow = 3, 
  labels = c("a", "b", "c", "d", "e", "f"),
  label.x = 0.135,
  align = "hv")

ggsave("Figures/Figure3.png",dpi=600, height=7, width=8)
```

# Extract model correlation estimates

```{r}
colnames(posterior_samples(dhglm_N_skew))[1:11]
colnames(posterior_samples(dhglm_C_skew))[1:11]
colnames(posterior_samples(bivariate_model))[1:25]

corr_var_type_N <- posterior_samples(bivariate_model) %>% select("corr_N" = cor_whisker__scaleNraw_Intercept__sigma_scaleNraw_Intercept)

corr_var_type_C <- posterior_samples(bivariate_model) %>% select("corr_C" = cor_whisker__scaleCraw_Intercept__sigma_scaleCraw_Intercept)

corr_C_N_type <- posterior_samples(bivariate_model) %>% select("corr_C_N" = cor_whisker__scaleNraw_Intercept__scaleCraw_Intercept)

corr_C_N_var <- posterior_samples(bivariate_model) %>% select("corr_C_N_var" = cor_whisker__sigma_scaleNraw_Intercept__sigma_scaleCraw_Intercept)

corrs_df <- data_frame(Correlation = c("mean_N_rIIV_N",
                                      "mean_C_rIIV_C",
                                      "mean_N_mean_C",
                                      "rIIV_N_rIIV_C"),
                  Estimate = c(mean(corr_var_type_N$corr_N),
                               mean(corr_var_type_C$corr_C),
                               mean(corr_C_N_type$corr_C_N),
                               mean(corr_C_N_var$corr_C_N_var)),
                  Lower = c(HPDinterval(as.mcmc(corr_var_type_N$corr_N))[,"lower"],
                            HPDinterval(as.mcmc(corr_var_type_C$corr_C))[,"lower"],
                            HPDinterval(as.mcmc(corr_C_N_type$corr_C_N))[,"lower"],
                            HPDinterval(as.mcmc(corr_C_N_var$corr_C_N_var))[,"lower"]),
                  Upper = c(HPDinterval(as.mcmc(corr_var_type_N$corr_N))[,"upper"],
                            HPDinterval(as.mcmc(corr_var_type_C$corr_C))[,"upper"],
                            HPDinterval(as.mcmc(corr_C_N_type$corr_C_N))[,"upper"],
                            HPDinterval(as.mcmc(corr_C_N_var$corr_C_N_var))[,"upper"]))

# Results
corrs_df

# Plot correlation values with HPD intervals
ggplot(corrs_df, aes(x = Correlation, y = Estimate)) +
  geom_pointrange(aes(ymin = Lower,
                      ymax = Upper)) +
  geom_hline(yintercept = 0,
             linetype = "dotted",
             alpha = 0.3) +
  scale_x_discrete(limits = c("mean_N_rIIV_N",
                              "mean_C_rIIV_C",
                              "mean_N_mean_C",
                              "rIIV_N_rIIV_C"),
                   labels = c("δ15N:rIIVδ15N", "δ13C:rIIVδ13C", "δ15N:δ13C", "rIIVδ15N:rIIVδ13C")) +
  labs(x=NULL,
       y = "DHGLM Correlation (Estimate +/- 95% HPD)") +
  ylim(-1,1) +
  coord_flip() +
  theme_custom()

# ggsave("Figures/FigureS3.png", dpi=600, height=3, width=5)
```


















